language: r
cache: packages
r:
  - release

r_binary_packages:
  - devtools
  - rmarkdown
  - rjson
  - knitr
  - pacman

install:
  - R -e 'devtools::install_deps(dep = TRUE)'

script:
  - Rscript ./compiler.r
