language: r
cache: packages
r:
  - release

install:
  - R -e 'install.packages(c("devtools", "rmarkdown", "rjson", "knitr", "pacman"))'

script:
  - pwd
  - ls
  - cd articles && Rscript ./compiler.r
