---
title: Data - Congressional Parties
author: Voteview
description: This article describes the data fields made available in the "Congressional Parties" data download
original_date: "2018-08-01" # Set the original date of your contribution in YYYY-MM-DD format here.
date: "`r format(Sys.time(), '%B %d, %Y')`" # Do not modify this
tags:
  - help # Valid tags are: blog, help, data. You may use multiple tags for a post
---

## Congressional Party Data

The Congressional Party data export contains biographical information and ideological mean and median scores for congressional parties in the selected chamber(s) and congress(es).

Quick Link (all congresses, all chambers, CSV format):
[https://voteview.com/static/data/out/parties/HSall_parties.csv](https://voteview.com/static/data/out/parties/HSall_parties.csv)

### Biographical Fields:

* **congress**: Integer `1+`. The number of the congress that this member's row refers to. e.g. `115` for the 115th Congress (2017-2019)
* **chamber**: `House`, `Senate`, or `President`. The chamber in which the member served.
* **party_code**: Integer `1-9999`. Identifying code for the member's party. See below for a list mapping party codes to parties.
* **party_name**: String. The name of the party.
* **n_members**: Integer `1+`. Number of party members in this chamber in this congress.

### Party Codes

Party Code | Party Name
---------- | ----------
100 | Democratic Party
200 | Republican Party


Party Code | Party Name
---------- | -----------
1 | Federalist Party
13 | Democratic-Republican Party
22 | Adams Party
26 | Anti Masonic Party
29 | Whig Party
37 | Constitutional Unionist Party
44 | Nullifier Party
46 | States Rights Party
108 | Anti-Lecompton Democrats
112 | Conservative Party
114 | Readjuster Party
117 | Readjuster Democrats
203 | Unconditional Unionist Party
206 | Unionist Party
208 | Liberal Republican Party
213 | Progressive Republican Party
300 | Free Soil Party
310 | American Party
326 | National Greenbacker Party
340 | Populist PARTY
347 | Prohibitionist Party
354 | Silver Republican Party
355 | Union Labor Party
356 | Union Labor Party
370 | Progressive Party
380 | Socialist Party
402 | Liberal Party
403 | Law and Order Party
522 | American Labor Party
523 | American Labor Party (La Guardia)
537 | Farmer-Labor Party
555 | Jackson Party
1060 | Silver Party
1111 | Liberty Party
1116 | Conservative Republicans
1275 | Anti-Jacksonians
1346 | Jackson Republican
3333 | Opposition Party
3334 | Opposition Party (36th)
4000 | Anti-Administration Party
4444 | Constitutional Unionist Party
5000 | Pro-Administration Party
6000 | Crawford Federalist Party
7000 | Jackson Federalist Party
7777 | Crawford Republican Party
8000 | Adams-Clay Federalist Party
8888 | Adams-Clay Republican Party

Party Code | Party Name
---------- | -----------
328 | Independent
329 | Independent Democrat
331 | Independent Republican
603 | Independent Whig

### Ideological Fields:

* **dim1_median**: Median of the NOMINATE first dimension estimates among members of `party_code` in this `chamber` during `congress`.
* **dim2_median**: Median of the NOMINATE second dimension estimates among members of `party_code` in this `chamber` during `congress`.
* **dim1_median**: Mean of the NOMINATE first dimension estimates among members of `party_code` in this `chamber` during `congress`.
* **dim2_median**: Mean of the NOMINATE second dimension estimates among members of `party_code` in this `chamber` during `congress`.

## Citation

To cite this data, please use the following citation:

Lewis, Jeffrey B., Keith Poole, Howard Rosenthal, Adam Boche, Aaron Rudkin, and Luke Sonnet (`r format(Sys.time(), '%Y')`). *Voteview: Congressional Roll-Call Votes Database.* [https://voteview.com/](https://voteview.com/)
