---
title: Data - Members' Votes
author: Adam Boche
description: This article describes the data fields made available in the "Members' Votes" data download
original_date: "2018-08-01" # Set the original date of your contribution in YYYY-MM-DD format here.
date: "`r format(Sys.time(), '%B %d, %Y')`" # Do not modify this
tags:
  - help # Valid tags are: blog, help, data. You may use multiple tags for a post
---

## Members' Votes

This data contains basic information about how each member in the selected chamber(s) and congress(es) voted on each vote.

Quick Link (all congresses, all chambers, CSV format):
[https://voteview.com/static/data/out/votes/HSall_votes.csv](https://voteview.com/static/data/out/votes/HSall_votes.csv)

## Fields:

* **congress**: Integer `1+`. The number of the congress that this member's row refers to. e.g. `115` for the 115th Congress (2017-2019)
* **chamber**: `House`, `Senate`, or `President`. The chamber in which the member served.
* **rollnumber**: Integer `1+`. Starts from 1 in the first rollcall of each congress. Excludes quorum calls and vacated votes. 
* **icpsr**: Integer `1-99999`. This is an ID code which identifies the member in question. In general, each member receives a single ICPSR identifier applicable to their entire career. A small number of members have received more than one: this can occur for members who have switched parties; as well as members who subsequently become president. Creating a new identifier allows a new NOMINATE estimate to be produced for separate appearances of a member in different roles.
* **cast_code**: Integer `0-9`. Indicator of how the member voted.
* **prob**: Estimated probability, based on NOMINATE, of the member making the vote as recorded.

### Cast Codes

cast_code | Description
--------- | -----------
0 | Not a member of the chamber when this vote was taken
1 | Yea
2 | Paired Yea
3 | Announced Yea
4 | Announced Nay
5 | Paired Nay
6 | Nay
7 | Present (some Congresses)
8 | Present (some Congresses)
9 | Not Voting (Abstention)

## Citation

To cite this data, please use the following citation:

Lewis, Jeffrey B., Keith Poole, Howard Rosenthal, Adam Boche, Aaron Rudkin, and Luke Sonnet (`r format(Sys.time(), '%Y')`). *Voteview: Congressional Roll-Call Votes Database.* [https://voteview.com/](https://voteview.com/)
